// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6TRsrpzY8mYpfx5oSdSN-3QCIngbLbE',
    appId: '1:40758318040:android:b6cca24ad28f76dd1ad8ad',
    messagingSenderId: '40758318040',
    projectId: 'weather-app-9cb02',
    storageBucket: 'weather-app-9cb02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGNOBosd8Dn7VLteCPVfDsbbDy54OaDk',
    appId: '1:40758318040:ios:1a06e0081ae1722a1ad8ad',
    messagingSenderId: '40758318040',
    projectId: 'weather-app-9cb02',
    storageBucket: 'weather-app-9cb02.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsXcekphQ1VapxDGn2zlp09TaW9f2rBxY',
    appId: '1:40758318040:web:1ef267ee18e62a201ad8ad',
    messagingSenderId: '40758318040',
    projectId: 'weather-app-9cb02',
    authDomain: 'weather-app-9cb02.firebaseapp.com',
    storageBucket: 'weather-app-9cb02.firebasestorage.app',
    measurementId: 'G-53QK3205FR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsXcekphQ1VapxDGn2zlp09TaW9f2rBxY',
    appId: '1:40758318040:web:03d15051b65a0d651ad8ad',
    messagingSenderId: '40758318040',
    projectId: 'weather-app-9cb02',
    authDomain: 'weather-app-9cb02.firebaseapp.com',
    storageBucket: 'weather-app-9cb02.firebasestorage.app',
    measurementId: 'G-LC6BRXRDKE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApGNOBosd8Dn7VLteCPVfDsbbDy54OaDk',
    appId: '1:40758318040:ios:1a06e0081ae1722a1ad8ad',
    messagingSenderId: '40758318040',
    projectId: 'weather-app-9cb02',
    storageBucket: 'weather-app-9cb02.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

}